### ISSUE TITLE
Update brands (mostly German)

### ISSUE THREAD

**Issue by sami155** [chris-mosley/AmazonBrandFilterList#13]
Ansmann
AEG
Bauknecht
Beko
Bomann
Clatronik
Einhell
Engelbert Strauss
Haier
Hama
Hoover
Medion
Miele
Siemens
Teufel
TechniSat
Varta
Vorwerk
Würth
Whirlpool

**Comment by chris-mosley** [comment]
Thank you for this submission.  They have been added in list v13!
