### ISSUE TITLE
Suggestion: make it clear this is a WHITELIST

### ISSUE THREAD

**Issue by DigitalSorceress** [chris-mosley/AmazonBrandFilterList#20]
I was looking at this add-on and the list trying to determine..and it did only take a little bit of work to determine that the list in this case is a whitelist. Reason why was that I happened to be searching for a drafting chair and I do know a few legitimate brands - I was surprised to see that "HON" was being blocked / or more specifically not being allowed (though I could see that the name "HON" could appear to those who don't know office furniture as if it's one of those random "caps lock on, cat walks on keyboard brand names" used by the drop-ship sellers.)

However, it's not explicitly stated here - Suggestion is that you say it right in the submission guidelines to avoid any confusion: 
when someone is adding a brand it is because it's an actual brand to allow through, not to block.

**Comment by DigitalSorceress** [comment]
Sorry, I realized this might have been better as discussion? sorry if this was not the right place for this.

**Comment by chris-mosley** [comment]
Yeah you're probably right here.  I have it spelled out more explicitly in the repo for the addon itself.  But I'll add it to this readme tonight.

**Comment by chris-mosley** [comment]
As an aside this is great info because I've already run into several categories where I feel unqualified to determine what's spam.

A huge part of the reason I am trying to crowdsource this list is to help with exactly these kinds of scenarios.
