### ISSUE TITLE
Some more well-known brands, mostly from Europe and Germany

### ISSUE THREAD

**Issue by jospanier** [chris-mosley/AmazonBrandFilterList#34]
AC Infinity
AEG
AVM
AXE
AZdelivery
Abus
Aeroxon
Airwaves
Alpina
Alpine
Always
Ankerkraut
Anycubic
Arc'teryx
Ariel
Bauknecht
Bayer
Bebe
Beierdorf
Benning
Beurer
Beyerdynamic
Biobizz
Biotherm
Blistex
Blumat
Boveda
Bresser
Brio
Brüder Mannesmann
Burg-Wächter
Burt´S Bees
CMP
Celestron
Cherry
Chupa Chups
Clatronic
Clementoni
Compo
Continental
Coral
Curver
Dakine
De'Longhi
Dehner
Deuter
Devolo
Dewalt
Dove
Dr. Beckmann
Dr. Neuhaus
Dr. Oetker
Dreame
Dreamies
Dremel
Dunlop
Durable
Eastpak
Eberhard Faber
Eichhorn
Einhell
Emsa
Eppendorf
Eubos
Eucerin
Extech
Faber-Castell
Fackelmann
Felix
Festool
Fimo
Fischer
Fjällräven
Fluke
Folia
Franzis
Gardena
Garmin
Garnier
Gizeh
Gloria
Gorenje
Greenception
Haba
Hakle
Hama
Hansaplast
Hansgrohe
Hantek
Haribo
Hasbro
Heitmann
Herlitz
High Peak
Hipp
Hisense
Hybrid
Ifixit
Impresan
Jack Wolfskin
Jacobs
Kneipp
Knipex
Kokett
Kosmos
L'Oréal
Lacura
Lamy
Lancom
Lavazza
Leatherman
Leifheit
Leina
Lenor
Lipton
Liqui Moly
Läufer
M&M
Makita
Mammut
Manhattan
Mannol
Marabu
Marmot
Mars Hydro
Max Factor
Medion
Medisana
Meister
Melitta
Metabo
Midea
Miele
Milka
Molto
Neff
Nescafé
Nestlé
Neudorff
Nexa Lotte
Nigrin
Nivea
Nuk
OCB
Owon
Parker
Peaktech
Pelikan
Penaten
Persil
Perwoll
Pilot
Plantura
Play-Doh
Playmobil
Polar
Powerade
Pritt
Proxxon
Ravensburger
Raw
Redken
Relaxdays
Remington
Revlon
Rexona
Rigol
Rituals
Rotho
Rowenta
Ruf
Russell Hobbs
Rösle
Røde
Sagrotan
Samsonite
Sanlight
Satch
Schleich
Schmidt Spiele
Schneider
Schott
Schwalbe
Schöffel
Sebamed
Sennheiser
Seramis
Severin
Sheba
Shelly
Shimano
Sigma
Soehnle
Somat
Sonax
Spee
Spider Farmer
Stabilo
Staedtler
Stanley
Sterillium
Stihl
Substral
Sunil
Switchbot
TDK
TFA Dostmann
Tassimo
TechniSat
Teekanne
Tefal
Tesa
Tetesept
The North Face
Thomy
Tipp-Ex
TrekStor
Trigema
UHU
Uni-T
Unitec
Vileda
Villeroy & Boch
Viparspectra
Vitafit
Vitakraft
Voltcraft
Vtech
WD-40
Wago
Weißer Riese
Weleda
Wella
Wera
Whiskas
Wiha
Windhager
Wolf Garten
Worx
XLC
Yankee Candle
Zeiss
Zwilling

**Comment by chris-mosley** [comment]
This is merged.  Thanks!

Some of these, (Sunil being the main one I found) are making the case for region specific brand names.  

Sunil is known as Surf outside of the Netherlands.  I don't think this is urgent, and maybe it won't even matter.  But something to think about.

**Comment by jospanier** [comment]
Thanks!

**Comment by chris-mosley** [comment]
As an aside, was there a video or something that came out?  I'm having a bit of a surge of interest in the project and I'm just curious where it's coming from. :)

**Comment by jospanier** [comment]
Not aware of a video or other coverage. Just got fed up with junk on Amazon and started researching for Amazon filter add-ons. Et voilà, of course it exists. Your add-on is actually rated very high on https://addons.mozilla.org/firefox/search/?q=amazon+filter.
