### ISSUE TITLE
Adding Missing Brands. Mainly Consumer and Clothing brands from the USA.

### ISSUE THREAD

**Issue by JacobMH1** [chris-mosley/AmazonBrandFilterList#44]
5.11
5.11 Tactical
Always Discreet
Angel Soft
Anne Klein
AOC
ARIAT
Astro
AquaSonic
Aurora
Austin Air
Belk
Benevolence LA
Biolage
Birkenstock
Biscoff
Bissell
Blueair
Bounce
Bounty
C.C
C.C Beanie
Candle Warmers
Carefree
Celtic Sea Salt
Charmin
Corelle
Corning Ware
Corningware
Core Power
Cottonelle
Coway
Cremo
Dearfoams
Death Wish Coffee
DenTek
Depend
Dixie
Dooney & Bourke
Dooney and Bourke
Dr Pepper
Dubinik
eos
Escort
EXTRA
Feit Electric
Finish
GermGuardian
Gildan
glerups
Haflinger
Harry's
Henckels
Henson Shaving
Hey Dude
HEYDUDE
INSIGNIA
JCPenney
Kenwood
L.
La Jolie Muse
Lands’ End
Lands End
Lee
Levi Strauss
LEVOIT
L.L. Bean
LL Bean
Legendary Whitetails
Liquid Death
L'Oreal Paris
Lotus Biscoff
Lumify
Maruchan
Michael Korz
Minnetonka
Montana West
NICETOWN
OGX
Olaplex
Playtex
PopSockets
Premier Protein
PÜR
PUR
Pureology
Pyrex
REDMOND
Reynolds
Reynolds Kitchens
Roku
Sailwind
ScentSationals
Sceptre
Scosche
Scott
Selsun Blue
Sharp
Sonos
Sparkle
Stayfree
Sylvania
Systane
Tampax
The Honest Company
The Honey Pot Company
TheraBreath
Timex
Topo Chico
Trident
Turtle Beach
U by Kotex
UGG
Uniden
Vagisil
Vera Bradley
Vikings Blade
VIZIO
Wilton
Winix
Wrangler
Yokohama

**Comment by chris-mosley** [comment]
These have been added.  Thanks!

**Comment by JacobMH1** [comment]
Thank you! I am working on some more as we speak. Buying Christmas gifts will be a lot easier now.
