### ISSUE TITLE
Adding Missing Brands. Mainly USA Consumer Products

### ISSUE THREAD

**Issue by JacobMH1** [chris-mosley/AmazonBrandFilterList#46]
My last list included a spelling error for Michael Kors, I spelled it Michael Korz, with a "Z". If it could be replaced, that would be sweet. Thank you. I think I am going to take a break from staring at Amazon now.

I edited this post and added more at 5:00 PM CST.

AEROPOSTALE
American Crew
Anthony's
Bedsure
Billabong
Billie
BIOPURE
Blind Barber
Bob's Red Mill (Current item on list does not include apostrophe. Replace or include in addition)
Bostitch
Branch
Brawny
Brickell
Brickell Men's Products
Brooklinen
BUG-A-SALT
California Design Den
Cariloha
Cascadian Farm
Caseology
Chanel
ChapStick
Cheerios
Cheetos
Chex
Chubbies
Chubbies Shorts
ChubbyCable
Cinnamon Toast Crunch
Converse
Cream of Wheat
Cree
Cree Lighting
Curel
Doritos
Dude
Dude Wipes
ecotowel
EverBrite
Expo
Fiber One
Folgers
Frito Lay
Fromm
Fromm International
Froot Loops
Fruity PEBBLES
GAP
General Mills
GILDEN TREE
Gold Bond
Got2b
Gourmanity
Great Grains
Greenlite
Hairitage
Hammermill
Herb Guard
Herman Miller
Hugo
HUGO BOSS
Intex
Jack Link's
Johnny B
Johnny B.
Johnny Slicks
Kate Spade New York
Keebler
Kellogg's
Kettle Brand
KIND
King Koil
Kirkland
Kirkland Signature
Kix
Kodiak Cakes
Life
Louis Vuitton
MadeGood
Malt-O-Meal
MANSCAPED
Marc Anthony
Marc Jacobs
Maria Nila
Member's Mark
Michael Kors (REMOVE Michael Korz. Misspelling)
Mielle Organics
MightyGood
moleskine
Monster
Moroccanoil
Nabisco
Nature Valley
Nature's Path
Nexxus
Nizoral
NuTrail
Oats Overnight
Office Depot
One Degree
One Degree Organic Foods
Oreo
PanOxyl
Parachute
Peak Design
Pelican
Pendleton
Pepsi
PepsiCo
Philips Norelco
Pittman
Pittman Outdoors
POLO RALPH LAUREN
Post Foods
Post Foods LLC
Post-it
Pringles
Purely Elizabeth
Q-Tips
Quaker
Ralph Lauren
Red Land Cotton
Revlon
RhinoShield
ringke
RITZ
Russell Athletic
Salt Life
Schick Hydro Silk
Sebastian
Sebastian Professional
Secretlab
Sensodyne
SentrySafe
Serta
SexyHair
simplehuman
Skunk
Sky Organics
SnapSafe
Speedo
Stalwart
Staples
steelcase
STOPBOX
Suavecito
Sunco
Sunco Lighting
Surefire
The Good Crisp Company
The Spice Way
TIGI
Tommy Bahama
Tory Burch
Tree Hut
TRESemmé
True Classic
True Organic
TUL
Unilever
Utopia
Utopia Bedding
Utopia Towels
Valentino
VAULTEK
Vaultz
Wahl
Wet Ones
Zebralight

**Comment by chris-mosley** [comment]
Merged.  Thanks!
