### ISSUE TITLE
Adding missing brands. Camping, knives, clothing, electronics.

### ISSUE THREAD

**Issue by JacobMH1** [chris-mosley/AmazonBrandFilterList#49]
Arctic Zone
BAOFENG [On the Fence. Up to you](https://www.baofengradio.com/pages/about-us)
Buck Knives
ByronStatics [On the Fence. Up to you](https://www.byronstatics.com/about/)
Califone
GCI Outdoor
Comfort Colors
Craig
Eberlestock
Emerson
FiiO [On the Fence. Up to you](https://www.fiio.com/About_FiiO)
Gerber Gear
GPX
Haggar
Hamilton
Hamilton Buhl
Hot Topic
HotHands
HydroJug
JENSEN
LifeStraw
Loungefly
Magnavox
Maxell
Midland
Mixxtape
Motorola Solutions
Naturehike [On the Fence. Up to you.](http://www.naturehike.com/pages/about)
Nextmug
Owala
OZARK TRAIL
Paul Fredrick
Poo-Pourri
Southpole
SlumberPod
Stansport
Studebaker
Swiss Eagle
Titan by Arctic Zone
Thread Wallets
Uncle Henry
Under the Weather
UNIONBAY
Van Heusen
VEET
Victrola
WeatherPod
Weatherproof Vintage

**Comment by chris-mosley** [comment]
Ended up adding all of these.

Boafeng has been around since at least 2012,
 Byronstatics is actually the one im least sure about but they're offered at walmart so eh.  
FiiO is a well known brand I'm surprised I didnt have already
Naturehike seems to have decent cred when I looked around.
