### ISSUE TITLE
Adding missing brands. 12.22.24

### ISSUE THREAD

**Issue by JacobMH1** [chris-mosley/AmazonBrandFilterList#52]
Alexander Del Rossa
Allstar Innovations
Alpine Swiss
Amco
Arus
Balega
BCBGMAXAZRIA (Looks sketch. It is real, I had never heard of it)
bella
Ben Sherman
Bloomingville
Blue Diamond
Body Glove
Bogey Bros
BOSS
Brightech
Brooks Brothers
Built
Caraway
CAROTE
Casper
Chef'n
Chicago Metallic
Children's Factory
CleverMade
Copco
Craft
Creative Co-Op
EUREKA
Fanttik [On the Fence. Up to you](https://fanttik.com/pages/about-us)
Finch + Fennel
Fitz & Floyd
Fitz and Floyd
Gentle Souls
Genuine Fred
Globe Electric
GOLDTOE
Gotham Steel
GreenPan
Healing Solutions
Hoffritz
hOmeLabs
Honey-Can-Do
Household Essentials
ILLUME
International Silver
IZOD
Jerzees
JONATHAN Y
Kenneth Cole
Kensington
Kizmos
Lacoste
Lands' End (Replace Lands’ End. Fixing the directional apostrophe)
Lifetime Brands Inc.
LUXRITE
Made In
madesmart
MARQUESS
MARTHA STEWART
Melannco
Merten & Storck
Mikasa
Miracase
Misto
Mountain Hardwear
Mueller
Mueller Living
Munchkin
OttLite
Pfaltzgraff
Photo Paper Direct
Pitaka [On the Fence. Up to you](https://www.ipitaka.com/pages/about-us)
PlanetBox
PPD
PurSteam
R&B Wire
R&B Wire Products
Rabbit
Real Essentials
Rhone
S'well
Sabatier
Seville Classics
Shop-Vac
Signature Design by Ashley
Sleek Socket
Smartish
Spalding
Spicy Shelf
Squatty Potty
StoveShelf
Taylor
Thermajane
ThisWorx
Tipsy Elves
Titan
TORRAS [On the Fence. Up to you](https://torraslife.com/pages/about-us-1)
Towle
Towle Living
Tramontina
True Religion
Walker Edison
Wallace
Whitmor
Wilton Armetale
WiZ
WiZ Connected
Year & Day
Year and Day

**Comment by chris-mosley** [comment]
I left out the three on the fence entries
